flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:reflex-frp/reflex-dom.git
    commit: 59100d61282fe02aa39be602f0a73daf31e28f63
  extra-dep: true
- location:
    git: git@github.com:reflex-frp/reflex.git
    commit: 02cf9dbc89ba20b6e93622e0910a76d5e9d06669
  extra-dep: true
extra-deps:
- ghcjs-dom-0.2.4.0
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- webkitgtk3-javascriptcore-0.13.2.0
- sdl2-image-2.0.0
resolver: lts-7.21
