flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:reflex-frp/reflex.git
    commit: a1092192c61f3dec924a8e2686dfe3440681bab3
  extra-dep: true
extra-deps:
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- sdl2-image-2.0.0
- lens-4.15.3
resolver: lts-8.22
